repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
            exclude: clusters/homelab-flex-a1/
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.18.0
      hooks:
          - id: gitleaks
