---
- name: Ensure that a base set of software packages are installed.
  apt:
      update_cache: yes
      pkg:
          - build-essential
          - curl
          - git
          - htop
          - needrestart
          - net-tools
          - unzip
      state: latest
- name: Update apt-cache and do dist upgrade
  apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: dist
- name: Check if reboot required
  stat:
      path: /var/run/reboot-required
  register: reboot_required_file
- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true
