---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: selfsigned
    namespace: cert-manager
spec:
    selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-staging
    namespace: cert-manager
spec:
    acme:
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        email: franopusz2006@gmail.com
        privateKeySecretRef:
            name: letsencrypt-staging
        solvers:
            - http01:
                  ingress:
                      class: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
    namespace: cert-manager
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: franopusz2006@gmail.com
        privateKeySecretRef:
            name: letsencrypt-prod
        solvers:
            - http01:
                  ingress:
                      class: traefik
