kind: Service
apiVersion: v1
metadata:
    name: nginx-service
    namespace: default
spec:
    selector:
        app: nginx
    ports:
        - protocol: http
          port: 80
          targetPort: 80
