apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - ns.yaml
    - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    - ingress.yaml

## changes to config maps
patchesStrategicMerge:
    - argocd-config.yaml

namespace: argocd
